{% set name = "atpbar" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d148749476f646021faddf79b50de0e0b1b2258fb9cfe07db551b40006bbaa07

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
  run_constrained:
    - jupyter
    - ipywidgets
    - widgetsnbextension

test:
  imports:
    - atpbar

about:
  home: https://github.com/alphatwirl/atpbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Progress bars for threading and multiprocessing tasks on terminal and Jupyter Notebook'
  description: |
    atpbar can display multiple progress bars simultaneously growing
    to show the progresses of iterations of loops in threading or
    multiprocessing tasks on terminal and Jupyter Notebook.
  dev_url: https://github.com/alphatwirl/atpbar
  doc_url: https://github.com/alphatwirl/atpbar#atpbar

extra:
  recipe-maintainers:
    - TaiSakuma
