{% set name = "atpbar" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4e6e47e70ef39dc646a507859da109239ed35e4e9d1862da32cc0ba58760d7b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
  run_constrained:
    - jupyter
    - ipywidgets
    - widgetsnbextension

test:
  imports:
    - atpbar

about:
  home: https://github.com/alphatwirl/atpbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Progress bars for threading and multiprocessing tasks on terminal and Jupyter Notebook
  description: |
    atpbar can display multiple progress bars simultaneously growing
    to show the progresses of iterations of loops in threading or
    multiprocessing tasks on terminal and Jupyter Notebook.
  dev_url: https://github.com/alphatwirl/atpbar
  doc_url: https://github.com/alphatwirl/atpbar#atpbar

extra:
  recipe-maintainers:
    - TaiSakuma
