travis:
  secure:
    BINSTAR_TOKEN: FR+IRTme5/iH8M3Qj0FgNfiCtLley4gQh22O3zisZ8YtYj8mUzQdXXDYw9GgbIof/OEjsqDTx4BeQT1MvC3Ooq4jxJJST6nRvSl2doKDuSNBzS8gonPq/cp05pZRhBo7WYZMckDJh11dpAm03tOWkZqnQr8k875yyy7QDpRT1XQpRPQOUMxtZ65EYe1xTysFqtOXYxKF2zIcZVVXRYp0T+ATGmZJnTflN+uOEurid4ETrj0LgdJ5uAUHSsS7w4je2xrrt32Z+mxyhW3WEk2vgS6exWithGfYojiXP1l+bZY+K19eMH4LKW4eN679iq3CxV6Q1vDiH1NVsPgSCezcCn3Pgw21vXmAJvHWB+tEaLvufuxsnZQSnas45ZTBzSu13Lr6IoFtu/tt5KF6+fvymlQ5FeS0PAWsIkl13BSAWJYH4K0pLyV5lQ1HJvL+I7P0mITAIhRBYyeAeMXLQri57/U43HS+e2FIR7b/3+gOIWLONmXjQ2p2ps3/rKkYdvEHvnnu6tcjwKn97hVpBbBXY/GbQzq13k5960qQS57N11TnBg06DOPl3/eWeLwPUv1AnZ8Z3l1MxMo+VKoYv+Fp34LRR2OcHBopDtDgmpmJjoYV9GCyWdTwBaf2rxn7DNdmHmw506t+n/a/UNUq8fLDRSGBqPIepzhpkrklnTl5LAs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
